hmcts/jenkins-packer

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/DTSPO-9917
```
[ ] Yes
[x] No
```

Set get_azure_image_version.azure_image_version output

---

azure-pipelines.yml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

Revert to GitHubRelease@1 task

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/DTSPO-10770
Fix method to retrieve latest version from image gallery
```
[ ] Yes
[x] No
```

DTSPO-10770 - Fix method to retrieve latest version from image gallery

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/DTSPO-10747
Update azure-pipelines.yml with changed tagSource
```
[ ] Yes
[x] No
```

DTSPO-10747 - Update azure-pipelines.yml

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/DTSPO-9917
Include release notes
```
[ ] Yes
[X] No
```

DTSPO-9917 - Include release notes

---

azure-pipelines.yml

DTSPO-9917
Add releaseNotesSource
```
[ ] Yes
[X] No
```

DTSPO-9917 - Add releaseNotesSource

---

azure-pipelines.yml
provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-11883
Fix failsafe deletion step in pipeline.
`--yes` is required for automatic confirmation to delete resource group via azure cli

DTSPO-11883 - fix deletion step

---

azure-pipelines.yml
provision-jenkins-ubuntu-agent.sh

Fix error with unzip requesting input to overwrite
Updates `apt remove` logic to avoid errors
Add logic to delete packer resource groups that linger after a run is cancelled
```
[ ] Yes
[x] No
```

Fix errors

---

azure-pipelines.yml
jenkins-agent-ubuntu.pkr.hcl
provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-12193
Add helm, kubectl and flux
```
[ ] Yes
[x] No
```

DTSPO-12193 - Add flux, helm, kubectl

---

README.md
provision-jenkins-ubuntu-agent.sh
renovate.json

https://tools.hmcts.net/jira/browse/DTSPO-12193
Add renovate config for regex
Enables renovate to detect updates for utilities in script and update them via pull request
See example renovate jobs https://developer.mend.io/github/hmcts/ek-test-repo
See example dependency dashboard https://github.com/hmcts/ek-test-repo/issues/1
```
[ ] Yes
[x] No
```

DTSPO-12193 - Update renovate config

---

provision-jenkins-ubuntu-agent.sh

No longer needed as of August 1st https://github.com/hmcts/cnp-jenkins-library/blob/d5ca287adaa9ce2f48db390e89c6d85459672202/src/uk/gov/hmcts/contino/GradleBuilder.groovy#L257

Remove Java 11

---

jenkins-agent-ubuntu.pkr.hcl

https://tools.hmcts.net/jira/browse/DTSPO-14034
Remove managed_image_name from master build and publish
```
[ ] Yes
[x] No
```

DTSPO-14034 - Remove managed_image_name

---

provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-14034
Add cross platform zaproxy binary
```
[ ] Yes
[x] No
```

DTSPO-14034 - Add zaproxy

---

provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-14034
Use chmod to update permissions on azcopy binary
Not currently executable on jenkins agents
```
[ ] Yes
[x] No
```

DTSPO-14034 - Make AzCopy executable

---

provision-jenkins-ubuntu-agent.sh

DTSPO-15526
Testing of new .yarn location with Jenkins arm agents as these are not currently in use by other teams.

testing yarn folder move on jenkins arm agents

---

provision-jenkins-ubuntu-agent.sh

DTSPO-15526
New permissions for yarn testing

DTSPO-15526 - testing yarn permissions

---

provision-jenkins-ubuntu-agent.sh

Just to make things a bit nicer with regard to type hinting
Upgraded python from default 20.04 LTS version (3.8.10) to 3.10.11

Python 3.10

---

provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-15526
Set ownership of folder to jenkins user

DTSPO-15526 - update ownership

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/DTSPO-15526
Variable is no longer being set after moving release into dedicated job
Updating the job so the value gets passed in

Fix azure image version variable

---

provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-15526
Add /opt/app folder to match folder used in cnp-node-base docker container

DTSPO-15526 - Add /opt/app folder

---

provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-17285
Adding ffmpeg to allow teams to do audio transcoding

Adding ffmpeg to allow teams to do audio transcoding

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/DTSPO-17999
- Removes arm build from packer config

Dtspo 17999 remove arm jenkins agents

---

README.md
azure-pipelines.yml
jenkins-agent-ubuntu.pkr.hcl
provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-23199
- Updates `image_offer` and `image_sku` to build image with Ubuntu 24.04 LTS
- Updates provisioning script to work with 24.04
- Tested on `ptlsbox` by running plum pipelines

Upgrade ubuntu to 24.04 lts

---

azure-pipelines.yml
provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-23199
- Ran into an issue where a PR image got picked up by renovate and applied to Jenkins
- Updated the pipeline with a variable `major_verison` which will be used to determine the version for master builds e.g. `24.0.1`
- PR images will continue to use the PR number e.g. `245.0.0`
- A new GitHub release will only be created for images beginning with `$(major_version).` which should prevent PR images from being picked up by renovate
- Add line to provisioning script to fix issue with puppeteer in newer versions of Ubuntu - https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md#option-3_the-safest-way

Update versioning of images created by pipeline

---

azure-pipelines.yml
provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-23199
- Applying a fix for the new ubuntu 24.04 image as theres an issue running puppeteer on versions after 23.10
- Removing the condition from release stage as included in `--query` argument of az cli command earlier in the pipeline, making it obsolete.
- Prevented a release from getting created in previous pipeline run.

Test fix for Puppeteer on Ubuntu 24.04

---

provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-24175
- Pipeline reporting missing dependencies at cross-browser test stage
- Installing them via provisioning script
- Wasn't caught during testing as plum/toffee don't have a cross-browser test stage

Install missing dependencies

---

azure-pipelines.yml
jenkins-agent-ubuntu.pkr.hcl
provision-jenkins-ubuntu-agent.sh

- Reverting Jenkins Packer image and pipeline to previous state due to compatibility issues with Ubuntu24.04
- Plan to redo the upgrade after teams have brought dependencies into allignment

Revert script and pipeline to before ubuntu24

---

azure-pipelines.yml
jenkins-agent-ubuntu.pkr.hcl
provision-jenkins-ubuntu-agent.sh

https://tools.hmcts.net/jira/browse/DTSPO-23199
- Upgrading Ubuntu to 24.04 after pa11y/puppeteer deprecation date which was previously blocking
- Have added a packer init step to pipeline and defined azure plugin version to allow creating standard public ip instead of basic which will be EOL soon

Upgrade Ubuntu in Jenkins Packer images

---

azure-pipelines.yml
jenkins-agent-ubuntu.pkr.hcl
provision-jenkins-ubuntu-agent.sh

Pull SSH key from keyvault instead of using variable in ADO
SSH key has been regenerated
Update script so SSH key is not exposed in logs by moving the `set -xe` command
Tested the image on sandbox jenkins yesterday and it worked the same. Nothing has changed apart from the key.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

Update set commands and refresh ssh key

---

README.md
azure-pipelines.yml

Add info to readme on ssh key changes
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

Add info to readme on ssh key changes

---

README.md

See [DTSPO-26431](https://tools.hmcts.net/jira/browse/DTSPO-26431)
Add more info to readme on how to renew the SSH key used in the image
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

DTSPO-26431 - Add more info to readme on ssh setup
